#!/usr/bin/env python3
"""Extract code-list identifiers from refers/ genericode into generated_codes.rs.

CEN/Peppol XML stays gitignored (EUPL). The output is MIT OR Apache-2.0:
code points only, generated, do not edit.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INV = ROOT / "refers/pint-my-1.3.0/unpacked/trn-invoice/codelist"
CN = ROOT / "refers/pint-my-1.3.0/unpacked/trn-creditnote/codelist"
OUT = ROOT / "crates/core-invoice/src/generated_codes.rs"
PINS = "PINT-MY 1.3.0 gc; Peppol BIS v3.0.20 UNCL 5305 tokenize; EN validation-1.3.16"


def gc_ids(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8")
    ids: list[str] = []
    seen: set[str] = set()
    for m in re.finditer(
        r'ColumnRef="id">\s*<gc:SimpleValue>([^<]+)</gc:SimpleValue>', text
    ):
        v = m.group(1).strip()
        if v and v not in seen:
            seen.add(v)
            ids.append(v)
    if not ids:
        raise SystemExit(f"no codes in {path}")
    return ids


def rust_arr(name: str, ids: list[str], extra: list[str] | None = None) -> str:
    seen = set(ids)
    if extra:
        for e in extra:
            if e not in seen:
                ids.append(e)
                seen.add(e)
    body = ",\n".join(f'    "{i}"' for i in ids)
    return f"pub static {name}: &[&str] = &[\n{body},\n];\n"


def main() -> int:
    if not INV.is_dir():
        print(f"missing {INV}; keep last generated file", file=sys.stderr)
        return 0 if OUT.exists() else 1
    cn_path = INV / "UNCL1001-cn.gc"
    if not cn_path.exists():
        cn_path = CN / "UNCL1001-cn.gc"
    parts = [
        "// @generated by xtask/gen_codes.py. Do not edit.",
        f"// Pin: {PINS}. Code points only — not the EUPL genericode XML.",
        "",
        # XXX is ISO 4217 "no currency"; Peppol tokenize also includes CNH.
        rust_arr("ISO_4217", gc_ids(INV / "ISO4217.gc"), extra=["XXX", "CNH"]),
        rust_arr("ISO_3166", gc_ids(INV / "ISO3166.gc")),
        # EN 16931 BR-CL-25 also lists letter EAS codes EM AN AQ AS AU.
        rust_arr("EAS", gc_ids(INV / "eas.gc"), extra=["AN", "AQ", "AS", "AU", "EM"]),
        # EN BR-CL-01 includes 326/384 (corrective) and 389 (self-billed). Peppol P0100 still forbids 389.
        rust_arr(
            "UNCL_1001_INVOICE",
            gc_ids(INV / "UNCL1001-inv.gc"),
            extra=["326", "384", "389"],
        ),
        rust_arr("UNCL_1001_CREDIT_NOTE", gc_ids(cn_path)),
        # Z01/Z03–Z08 are PINT-MY extras on BT-81, not UNCL 4461 membership for EN/Peppol.
        rust_arr(
            "UNCL_4461",
            [c for c in gc_ids(INV / "UNCL4461.gc") if not (c.startswith("Z") and c != "ZZZ")],
        ),
        rust_arr("UNCL_5189", gc_ids(INV / "UNCL5189.gc")),
        rust_arr("UNCL_7161", gc_ids(INV / "UNCL7161.gc")),
        rust_arr("UNCL_2005", gc_ids(INV / "UNCL2005.gc")),
        rust_arr("UNCL_7143", gc_ids(INV / "UNCL7143.gc")),
        rust_arr("UNCL_1153", gc_ids(INV / "UNCL1153.gc")),
        rust_arr("ICD", gc_ids(INV / "ICD.gc")),
        rust_arr("REC20", gc_ids(INV / "UNECERec20.gc")),
        rust_arr("MIME", gc_ids(INV / "MimeCode.gc")),
        rust_arr("PINT_MY_TAXCAT", gc_ids(INV / "Aligned-TaxCategoryCodes.gc")),
        # Peppol BIS UBL.sch UNCL 5305 tokenize — VAT categories, not PINT-MY TaxCat.
        'pub static UNCL_5305: &[&str] = &["AE", "E", "S", "Z", "G", "O", "K", "L", "M", "B"];\n',
        """pub static VATEX: &[&str] = &[
    "VATEX-EU-79-C",
    "VATEX-EU-132",
    "VATEX-EU-143",
    "VATEX-EU-148",
    "VATEX-EU-151",
    "VATEX-EU-309",
    "VATEX-EU-AE",
    "VATEX-EU-D",
    "VATEX-EU-F",
    "VATEX-EU-G",
    "VATEX-EU-I",
    "VATEX-EU-IC",
    "VATEX-EU-J",
    "VATEX-EU-O",
    "VATEX-FR-FRANCHISE",
    "VATEX-FR-CNWVAT",
];
""",
    ]
    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
